version: '3.9'

services:
  app:
    build: ./docker/app
    container_name: blog_app
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_HOME: /composer
    volumes:
      - ./src:/workdir
    working_dir: /workdir
  web:
    image: nginx:1.20-alpine
    container_name: blog_web
    ports:
      - 8000:80
    volumes:
      - ./src:/workdir
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /workdir
  db:
    image: mysql:8.0
    container_name: blog_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/my.cnf:/etc/my.cnf
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
